highlightItems = (item_id, start_date) ->
  item_rows = $('.manage_index tr')
  item_rows.each (i, row) ->
    jquery_row = $(this)
    row_item_id = jquery_row.find('.item-id').val()
    row_start_date = jquery_row.find('.start-date').val()
    if row_item_id == item_id and row_start_date == start_date
      jquery_row.removeClass 'info success danger'
      jquery_row.attr 'style', 'background-color: yellow'
    return
  return

highlightCalendar = (item_id, start_date) ->
  $('.has-events .item_format').each ->
    day_item_id = $(this).find('#item_id').val()
    day_start_date = $(this).find('#start_date').val()
    if item_id == day_item_id and start_date == day_start_date
      borrowing_day = $(this).closest('.has-events')
      borrowing_day.attr 'style', 'background-color: yellow'
    return
  return

$(document).on 'ready turbolinks:load', ->
  events_bg_color = $('.has-events').css('background-color')
  table1_class = $('.manage_index .tr_table_1').attr('class')
  table2_class = $('.manage_index .tr_table_2').attr('class')
  # HOVER OVER CALENDAR
  $('.has-events').hover (->
    $(this).css 'background-color', 'yellow'
    all_items = $(this).find('.item_format')
    all_items.each (i, item) ->
      item_id = $(this).find('#item_id').val()
      start_date = $(this).find('#start_date').val()
      #highlightItems(data.value);    --- JS way
      highlightItems item_id, start_date
      return
    return
  ), ->
    $(this).css 'background-color', events_bg_color
    $('.manage_index .tr_table_1').each ->
      $(this).attr 'style', ''
      $(this).attr 'class', table1_class
      return
    $('.manage_index .tr_table_2').each ->
      $(this).attr 'style', ''
      $(this).attr 'class', table2_class
      return
    return
  # HOVER OVER 1st MANAGE TABLE ROWS
  $('.tr_table_1, .tr_table_2').hover (->
    $(this).removeClass 'info success danger'
    $(this).attr 'style', 'background-color: yellow'
    item_id = $(this).find('.item-id').val()
    start_date = $(this).find('.start-date').val()
    highlightCalendar item_id, start_date
    return
  ), ->
    if $(this).attr('class') == 'tr_table_1'
      $(this).attr 'class', table1_class
    if $(this).attr('class') == 'tr_table_2'
      $(this).attr 'class', table2_class
    $(this).attr 'style', ''
    $('.has-events').each ->
      $(this).css 'background-color', events_bg_color
      return
    return
  return

# ---
# generated by js2coffee 2.2.0
